12-26 19:54:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
12-26 19:54:32 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
12-26 19:54:32 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
12-26 19:54:32 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
12-26 19:54:32 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
12-26 19:54:32 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
12-26 19:54:32 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
12-26 19:54:32 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
12-26 19:54:32 jdbc[11]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
12-26 19:54:32 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
2020-04-11 16:32:27 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:242)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:182)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:189)
	at org.h2.jdbcx.JdbcDataSource.getConnection(JdbcDataSource.java:160)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 19 more
